spring.application.name=auth-service
server.port=3000
spring.config.import=optional:file:./config/secrets.properties

#OAuth2
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:3000/login/oauth2/code/google

#HARDCORE DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.boot.autoconfigure.security=DEBUG
#logging.level.org.springframework.security.oauth2=DEBUG
#logging.level.root=DEBUG